name: Build Java Paper Plugin (no Gradle, fixed API URL)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      PLUGIN_NAME: EconomyShopJava-1.0.0.jar
      PAPER_API_URL: https://api.papermc.io/v2/projects/paper/versions/1.21.1/builds/125/downloads/paper-1.21.1-125.jar

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Download Paper API (official API)
      run: |
        echo "Downloading Paper API from official API..."
        curl -L "$PAPER_API_URL" -o paper-api.jar
        ls -lh paper-api.jar

    - name: Compile sources with javac
      run: |
        mkdir -p out
        SRCS=$(git ls-files '*.java')
        echo "Compiling sources:"
        echo "$SRCS"
        javac -Xlint:unchecked -cp paper-api.jar -d out $SRCS

    - name: Add plugin.yml & config.yml into jar
      run: |
        cp plugin.yml out/
        [ -f config.yml ] && cp config.yml out/ || true
        cd out
        jar cf "../$PLUGIN_NAME" *
        cd ..
        ls -lh "$PLUGIN_NAME"

    - name: Upload jar artifact
      uses: actions/upload-artifact@v4
      with:
        name: EconomyShopJava-jar
        path: ${{ github.workspace }}/${{ env.PLUGIN_NAME }}
