name: Build Paper Plugin

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew || true

    - name: Build plugin
      run: ./gradlew clean build --no-daemon

    - name: Upload built jar
      uses: actions/upload-artifact@v4
      with:
        name: EconomyShopJava-jar
        path: build/libs/*.jar



        
